# Header
menu:
  Home: /
  About: /about
  Resume: /resume.pdf
linkedin: https://www.linkedin.com
twitter: https://www.twitter.com
github: https://www.github.com
youtube: https://www.youtube.com
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
# - tag
# - archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
google_plus:
fb_admins:
fb_app_id:
